### ISSUE TITLE
correct attachment embedding in widget

### ISSUE THREAD

**Issue by XCanG** [widgetbot-io/widgetbot#15]
Currently any attachment to the message embed as image (`<img>` tag), but if you post with message music or video, i.e. mp3, mp4, webm, then it will show wrongly in widget:
![default](https://user-images.githubusercontent.com/4011523/43128959-b5d2ce1a-8f4c-11e8-892d-ae5903194869.png)
(here is mp3 attachment)

**Comment by advaith1** [comment]
fixed in beta
