### ISSUE TITLE
After disabling all read permissions, all channels are still visible in the widget

### ISSUE THREAD

**Issue by noisy** [widgetbot-io/widgetbot#32]
![selection_999 217](https://user-images.githubusercontent.com/201263/46169065-66c8fc00-c29a-11e8-8d2d-d8408e6e13b4.png)

Users may feel, like a widget is broken, because they will not be able to load channels:

![selection_999 219](https://user-images.githubusercontent.com/201263/46169174-9f68d580-c29a-11e8-8e41-633748f710f2.png)

What is interesting... some channels is loading (cache from earlier attempts??), but (correctly), widget not allow send any messages if write permission is restricted: 
![selection_999 218](https://user-images.githubusercontent.com/201263/46169095-79433580-c29a-11e8-9a5b-5490d1e53c93.png)

but... desired effect is.. to only show channels, to which read permission is given.

**Comment by advaith1** [comment]
Resolved in support server, due to misconfigured permissions.
