### ISSUE TITLE
server crashing/unstable

### ISSUE THREAD

**Issue by hodgef** [widgetbot-io/widgetbot#42]
I was having difficulties setting the bot on my discord server, even after inviting the bot with all permisions. Then, the main website started showing 5XX errors intermittently.

![image](https://user-images.githubusercontent.com/25509135/46932456-e2a6a080-d01d-11e8-8297-2bebcadcf385.png)

![image](https://user-images.githubusercontent.com/25509135/46932580-5cd72500-d01e-11e8-9085-9df838eec95c.png)

![image](https://user-images.githubusercontent.com/25509135/46932589-6791ba00-d01e-11e8-8d79-52d9d94e956f.png)

Any idea if this can be fixed soon?

Thank you

**Comment by advaith1** [comment]
Switch to a cluster: https://docs.widgetbot.io/guides/move-to-cluster/

We recommend you don't use closer 2 since it's under the most load.

**Comment by hodgef** [comment]
Perfect, thanks for the clarification
