### ISSUE TITLE
embed has wrong theme colors

### ISSUE THREAD

**Issue by hodgef** [widgetbot-io/widgetbot#43]
Seemingly overnight, the chat embed appears to have some random colors I did not add.

![image](https://user-images.githubusercontent.com/25509135/47052834-2d3c3000-d178-11e8-8aab-cd2cc25a7bf2.png)

There doesn't seem to be any configs to change this. Any idea on how to fix it?

Embed link:
https://cl4.widgetbot.io/channels/498978399801573396/501410079694913537/

**Comment by advaith1** [comment]
fixed, thanks for the report 👍

**Comment by hodgef** [comment]
Thanks a lot for the speedy fix @advaith1
