### ISSUE TITLE
widget directing to old github "samdenty99"

### ISSUE THREAD

**Issue by Dani3lNL** [widgetbot-io/widgetbot#47]
As title says, the small button of Sam in the widget redirects to his old github profile.

**Comment by advaith1** [comment]
It goes to `https://samdd.me/r?github`, @samdenty would need to update the redirect on his own site.

**Comment by Dani3lNL** [comment]
What do you mean by "on his own site" ?

**Comment by advaith1** [comment]
`https://samdd.me/r?github` is a URL on his site, he needs to make that point to his new profile
