### ISSUE TITLE
When people write a mention, only a number appears

### ISSUE THREAD

**Issue by Dani3lNL** [widgetbot-io/widgetbot#48]
instead of @Fred for example, only @29340040329 or @!29340040329 appears.

**Comment by advaith1** [comment]
Known and fixed in latest version

**Comment by Dani3lNL** [comment]
thanks!! 👍

**Comment by Dani3lNL** [comment]
Do widget-hosts have to manually download and install latest version? Or will it auto-update for them somehow?

**Comment by advaith1** [comment]
Are you talking about the official hosted version or users self-hosting it?

**Comment by Dani3lNL** [comment]
Self hosted. What is the link to the official hosted one?

**Comment by advaith1** [comment]
https://docs.widgetbot.io/tutorial

You currently can't self-host the server unless you're a Patron, are you currently self-hosting the embed, and if so what branch are you using?

Also for support please [join the server](https://discord.gg/NYBEhN7).
