### ISSUE TITLE
join button sends me to defaultInvite (mpMQCuj), not my server

### ISSUE THREAD

**Issue by j2l** [widgetbot-io/widgetbot#49]
Ok, I just successfully made a discord widget.
But on one of my phones, I can't have the join button to work correctly.
I must admit I have a weird setup since it's on an old mobile (Android 5.1.1) embedding a firewall and XPrivacy (both blocking some on-the-fly looping).
Looks like the [invite](https://github.com/widgetbot-io/widgetbot/blob/62f14b6786cf5c447cc56bce1519bd3e204c0e27/packages/embed/src/views/Messages/Header/index.tsx) should be re-written to my server but it's not working in my case.
Always sending me to the invite page for WidgetBot.io (from samdd).

**Comment by advaith1** [comment]
Probably something on the phone is blocking the JavaScript from changing the invite. We can't really fix issues that only occur on one device; however if you figure out what's causing it then we may be able to investigate this further.

**Comment by advaith1** [comment]
I've heard of it going to the WidgetBot when pop-ups are disabled in the browser, but I don't know if that can also happen on mobile. Also the server is English-only.
