### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by hodgef** [widgetbot-io/widgetbot#50]
Hello, at the time of posting it seems the whole service is down (cl2, cl4...). Service is normally quite intermittent and not fully reliable. Is there a way you can open-source the self-hosting option and perhaps ask for support on patreon? Maybe make the managed hosting a paid option and the self host open source instead? I think free self-hosting will take a lot of load off your servers. Otherwise it'd be nice to know if this outage is taken care of.

Thank you

![capture](https://user-images.githubusercontent.com/25509135/48368256-3ccc6d00-e681-11e8-93f5-26adbfc52c5d.PNG)
![captures2](https://user-images.githubusercontent.com/25509135/48368593-28d53b00-e682-11e8-8414-082d6998d3fc.PNG)

**Comment by advaith1** [comment]
Free self-hosting is planned. Also it looks like the [vip1](https://school-b.us/wbot-vip1) cluster is still fine.

**Comment by hodgef** [comment]
Thanks for that news, it's definitely a good step since manually changing clusters whenever one is saturated is not very practical. While a load balancer would help, I think it makes a lot of sense to make self hosting free and widgetbot.io hosting paid (since the users will be paying for their bandwidth).

If you want you can leave this issue open until the load issue is resolved, as others might just make a duplicate ticket. I'm content that the issue is acknowledged.

Regards

**Comment by advaith1** [comment]
I just heard we're almost ready to release the server source so it should be available soon. Also we've found the cause of the outage but only @samdenty can fix it because it's connected to his Discord account.

**Comment by advaith1** [comment]
Main site and clusters are back up!

**Comment by Argorate** [comment]
same bug here, it's normal?

**Comment by advaith1** [comment]
As it says in the updates channel in our server, WidgetBot is currently experiencing intermittent issues, so some clusters may not work at some times. Currently cluster 2 seems to be up the most.
