### ISSUE TITLE
Discord login

### ISSUE THREAD

**Issue by advaith1** [widgetbot-io/widgetbot#75]
Let users log in to the widget and send with their account

**Comment by Denis3d** [comment]
Want it too

**Comment by Andre601** [comment]
Could that perhaps be connected to the guilds verification level?
Like when it is medium or higher, that the widget will only have discord login by default and not allow you to chat with any kind of name.

And maybe have a seperate option for embed/crate (either a setting for the bot or in the html) to disable this feature (enable/disable the guest option)

**Comment by advaith1** [comment]
If we will add a way to force logging in, it will probably be a separate setting

**Comment by Guzim** [comment]
Hi everybody, 

First of all, thank you so much for this fantastic widget. It's so helpful. 
I appreciate it. 

I also would like to add the ability to write messages as identified user. Up to the site that embed the widget to provide the correct information (token, id, whatever, ...)

Let us know if there is an opportunity to get it.

**Comment by Andre601** [comment]
> Hi everybody,
> 
> First of all, thank you so much for this fantastic widget. It's so helpful.
> I appreciate it.
> 
> I also would like to add the ability to write messages as identified user. Up to the site that embed the widget to provide the correct information (token, id, whatever, ...)
> 
> Let us know if there is an opportunity to get it.

Uh... Did you actually see the labels of this issue?
One says "suggestion" meaning it is an enhancement of widgetbot and one says "help wanted" meaning it's currently not implemented and waits for a dev to add it. It is a planned feature that isn't implemented yet.

**Comment by ppeinsold** [comment]
@advaith1 how to get the v2 beta? Would love to test the login feature in my productive app!

**Comment by advaith1** [comment]
@ppeinsold you need to join the server and mention Daave asking him for access: https://discord.gg/SQayRQf

**Comment by advaith1** [comment]
done in v2 beta

**Comment by playdewu** [comment]
@advaith1 how to get v2 beta?

**Comment by advaith1** [comment]
it's currently closed but join our Discord server and read #join-beta, and ask to join when it's open again
