### ISSUE TITLE
Void

### ISSUE THREAD

**Issue by lazaridiscom** [widgetbot-io/widgetbot#77]

**Comment by advaith1** [comment]
what is this?

**Comment by lazaridiscom** [comment]
Issue #65 suggest to enhance the main README, but before you do that, you need to fix the overall documentation status in all projects (add LICENSE files, add basic READMEs etc.).

See additionally this https://github.com/widgetbot-io/widgetbot/issues/65#issuecomment-464789723

**Comment by Andre601** [comment]
I made a PR for the documentation repo, to add a more informative readme...

**Comment by lazaridiscom** [comment]
https://github.com/widgetbot-io/crate

dead-link in readme: https://github.com/widgetbot-io/widgetbot/tree/master/packages/crate

Action: change repo widgetbot to point to "master" branch by default (which should contain a stable version). Alternatively: just copy the latest stable to "master"

**Comment by advaith1** [comment]
Updating the branch names is planned.

**Comment by lazaridiscom** [comment]
Some other points: https://github.com/widgetbot-io/widgetbot/pull/87#issuecomment-467248886

**Comment by lazaridiscom** [comment]
A few final points:

* Add a "Usage Example"  (code snippet to include crate in a website, without much talk. Pointer to full tutorial)
* The thing is that it becomes not immediately clear if I need to run widgetbots-io stuff in order to include it on my site, or if a simple code-snippet is enough. Clarify this first.
  * especially if code-level work (build) is not needed: move README section "Development" to a separate file (especially if a typical user would not need to build/dig-into code).
* Don't blow up the README. Tiny snippets max., and pointers to tutorials/docs.

**Comment by Andre601** [comment]
I mean when you click on `crate` in the readme, you'll be forwarded to the npmjs page, that also contains an example of implementing the crate.
So the embed is more or less the only thing that needs a example to implement.

Also to point that out:
When you go to the corresponding directions of the crate and embed, you'll see readme's of those two that again, show examples of how to use, with a link to the documentation.
(This is at least the case for the crate. The embed needs an example tho...)

https://github.com/widgetbot-io/widgetbot/tree/2.5/packages/crate
