### ISSUE TITLE
Make html-embed support mobile

### ISSUE THREAD

**Issue by Andre601** [widgetbot-io/widgetbot#84]
The html-embed doesn't support mobile as of now.
It shows channels and such like on a desktop, which makes text fairly small snd hard to read.

While I understand that there is the crate, it still is a missed oportunity, since some people might want to have a dedicated page for the chat.

**Comment by advaith1** [comment]
html-embed works fine on mobile: https://math.is-rocket.science/548202094268776458.png
If it doesn't work on your site it's probably an issue with your site's code.

**Comment by Andre601** [comment]
It's just the default html embed inside body tags

**Comment by advaith1** [comment]
If the website isn't mobile compatible then of course the embed won't be mobile compatible, try adding the [viewport meta tag](https://web.dev/discoverable/fix-viewport-tag) which is needed to make a site mobile compatible.
