### ISSUE TITLE
Yarn Error

### ISSUE THREAD

**Issue by Kore-Development** [widgetbot-io/widgetbot#89]
I don't know if this is a problem with [Yarn](https://yarnpkg.com) or [fluidsonic/widgetbot](https://github.com/fluidsonic/widgetbot) but when I do `yarn build` I get this error.
[Click here for yarn-error.log](https://paste.ee/r/QfEbn/0). I installed [Yarn](https://yarnpkg.com) using [Scoop](https://scoop.sh/) and cloned [fluidsonic's fork](https://github.com/fluidsonic/widgetbot) into a folder onto my desktop.

**Comment by Kore-Development** [comment]
***Please help me!***

**Comment by advaith1** [comment]
For support please use the #self-hosting-support channel in the WidgetBot Discord server instead of creating an issue.

**Comment by Kore-Development** [comment]
Nevermind. I just had to do `yarn` *then* `yarn build`.

**Comment by advaith1** [comment]
Ah makes sense
