### ISSUE TITLE
Need to update packages - 63 vulns

### ISSUE THREAD

**Issue by wobberjack** [widgetbot-io/widgetbot#90]
Installed widget bot got this response

+ @widgetbot/react-embed@1.2.1
added 2099 packages from 642 contributors, removed 407 packages, updated 971 packages and audited 98694 packages in 210.72s
found 63 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

Can't do npm audit fix, responds have to do it manually. 

example 1/63 from audit report:

  Low             Regular Expression Denial of Service

  Package         braces

  Patched in      >=2.3.1

  Dependency of   react-scripts

  Path            react-scripts > babel-jest > babel-plugin-istanbul >
                  test-exclude > micromatch > braces

  More info       https://nodesecurity.io/advisories/786

Please fix.

**Comment by samdenty** [comment]
react-scripts is only used in development. If there is a package that has a vulnerability, it needs to be present in one of our outputted js bundles or required inside the server for us to investigate it
