### ISSUE TITLE
Crate - script injection vuln

### ISSUE THREAD

**Issue by wobberjack** [widgetbot-io/widgetbot#91]
The url inside the script for the html header embed, - https://cdn.jsdelivr.net/npm/@widgetbot/crate@3 contains an unsafe-eval vulnerability. If widgetbot loses control over the domain malicious script injection into my app can be done.

**Comment by samdenty** [comment]
Eval is only unsafe when used incorrectly. Here it's only used [here](https://github.com/widgetbot-io/widgetbot/blob/2.5/packages/crate/src/umd.ts) to allow you to put code inside the crate script tag. This is optional, and you can disable it by putting no-eval on the script tag

**Comment by Yomanz** [comment]
> Please use [Trustedtypes](https://web.dev/trusted-types/) to assign to innerHTML to allow authors using CSP to be able to use widgetbot seemlessly (no DOMPurify is needed since you know exactly what you are injecting). It just makes life easier for end users. Also some guidance on `no-eval` in docs will be nice!

If you make this into a separate issue. We can look into it.

**Comment by CxRes** [comment]
OK!
