### ISSUE TITLE
Add support to disable guest posting

### ISSUE THREAD

**Issue by stevendegroote** [widgetbot-io/widgetbot#93]
It would be good to have the possibility to disable posting a message in a channel through the widget.

As such, a website could show the chat messages live, but require users to join with a real user to chat along.

**Comment by advaith1** [comment]
This is already possible, join the discord server for support.

**Comment by james-munson** [comment]
how???

**Comment by advaith1** [comment]
Go to channel settings > permissions, add the WidgetBot user (not role), and set Send Messages to ❌. Screenshot: https://math.is-rocket.science/493125613624754177.png

Please ask support questions [on Discord](https://discord.gg/NYBEhN7) instead of on GitHub, the GitHub repo is for reporting bugs.
